version: 0.0.1.{build}
image: Visual Studio 2017

init:
  - cmake --version
  - msbuild /version

install:
  - mkdir dokan-1.0.3 && cd dokan-1.0.3
  - curl -L https://github.com/dokan-dev/dokany/releases/download/v1.0.3/dokan.zip -o dokan.zip
  - 7z x dokan.zip && rm dokan.zip
  - cd ..

platform:
  - x64

configuration:
  - Debug
  - RelWithDebInfo

build:
  project: ffsp.sln

before_build:
  - cmake -G "Visual Studio 15 2017 Win64" -DFFSP_BUILD_BENCHMARKS=OFF -DDOKAN_INCLUDE_DIR="dokan-1.0.3/x64/Msys2/include" -DDOKAN_LIB_DIR="dokan-1.0.3/x64/Release" .
