name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse-dev

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        Invoke-WebRequest -Uri https://github.com/dokan-dev/dokany/releases/download/v1.0.3/dokan.zip -OutFile dokan.zip
        Expand-Archive -Path dokan.zip -DestinationPath dokan
        echo "DOKAN_INCLUDE_DIR=${{ github.workspace }}/dokan/x64/Msys2/include" >> $env:GITHUB_ENV
        echo "DOKAN_LIB_DIR=${{ github.workspace }}/dokan/x64/Msys2/lib" >> $env:GITHUB_ENV

    - name: Configure CMake (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DDOKAN_INCLUDE_DIR="${{env.DOKAN_INCLUDE_DIR}}" -DDOKAN_LIB_DIR="${{env.DOKAN_LIB_DIR}}" -G "Visual Studio 17 2022" -A x64

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Release

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C Release
